# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerUI',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('human_choice', models.TextField(default='scissors_r.png')),
                ('AI_choice', models.TextField(default='scissors_r.png')),
                ('result_text', models.TextField(default='')),
                ('score_text', models.TextField(default='Счет: ')),
                ('human_story_choices', models.TextField(default='')),
                ('AI_story_choices', models.TextField(default='')),
                ('wins', models.IntegerField(default=0)),
                ('loses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
            ],
        ),
    ]
