# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170824_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerui',
            old_name='AI_choice',
            new_name='ai_choice',
        ),
        migrations.RenameField(
            model_name='playerui',
            old_name='AI_story_choices',
            new_name='ai_story_choices',
        ),
    ]
