# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170825_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerui',
            name='ai_choice',
            field=models.TextField(default='empty.png'),
        ),
        migrations.AlterField(
            model_name='playerui',
            name='human_choice',
            field=models.TextField(default='empty.png'),
        ),
        migrations.AlterField(
            model_name='playerui',
            name='result_text',
            field=models.TextField(default='\xa0'),
        ),
        migrations.AlterField(
            model_name='playerui',
            name='score_text',
            field=models.TextField(default='0:0'),
        ),
    ]
