# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170828_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStatistic',
            fields=[
                ('id', models.TextField(default='globals', primary_key=True, serialize=False)),
                ('pair_y_r', models.TextField(default='')),
                ('wins', models.IntegerField(default=0)),
                ('loses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('rocks', models.IntegerField(default=0)),
                ('papers', models.IntegerField(default=0)),
                ('scissors', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='playerui',
            name='sequence',
            field=models.TextField(default='0'),
        ),
    ]
